name: Configuration Change Deployed
on:
  issue_comment:
    types: [created]

jobs:
  mark_deployment:
    if: startsWith(github.event.comment.body, '!deployed')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run deploy script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
        run: python .configuration_change_automation/scripts/on_comment_deployed.py
